# Generated by Django 3.2.8 on 2021-10-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('CARD_N', models.CharField(max_length=9, null=True, unique=True)),
                ('First_Name', models.CharField(max_length=200, null=True)),
                ('Last_Name', models.CharField(max_length=200, null=True)),
                ('Citizenship', models.CharField(max_length=50, null=True)),
                ('SEX', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('Personal_N', models.CharField(max_length=11, null=True, unique=True)),
                ('Date_Of_Birth', models.DateField(blank=True, null=True)),
                ('Date_Of_Expiry', models.DateField(blank=True, null=True)),
                ('Place_Of_Birth', models.CharField(max_length=50, null=True)),
                ('Date_Of_Issue', models.DateField(blank=True, null=True)),
                ('Issueing_Authority', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
