# Generated by Django 3.2.8 on 2021-10-14 10:16

import card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20211014_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='CARD_N',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='Personal_N',
            field=models.CharField(max_length=11, null=True, validators=[card.models.only_int]),
        ),
    ]
